### ISSUE TITLE
-t 1 outputs giant broken modules

### ISSUE THREAD

**Issue by AbsurdBartholomew** [MCJack123/UnkrawerterGBA#4]
I'm trying to rip from The Sims: Bustin' Out, and setting the threshold to 1 gives me a few modules that I assume are sound effects (which is what I want, as well as jingles) but they're huge, being bigger than the actual ROM. They also don't play properly.

**Comment by MCJack123** [comment]
This is likely because it tried to rip using the newer Krawall version (since TS:BO doesn't have the version signature that other games do), but TS:BO uses the older format, so some fields got mangled in the process. Use the `-k` flag when ripping TS:BO to make it use the old version (this should give you 47 modules). (Or use the Japanese release, which does have the signature and works properly by default.)
