### ISSUE TITLE
Automatically convert instrument samples into soundfont files?

### ISSUE THREAD

**Issue by leopardheart982** [MCJack123/UnkrawerterGBA#5]
I wanna preface by saying I'm SO glad this program even exists! I was starting to think I would never be able to rip instruments from some of my old obscure GBA games. That said, I wish Unkraw could automatically output instrument samples to a .sf2 file because making a .sf2 manually from hundreds of instruments is a nightmare. Not sure how feasible this is, or if Unkraw is even still being worked on, but thought I'd ask.

**Comment by leopardheart982** [comment]
I should add, support for outputting songs to MIDI if possible would also be greatly appreciated. Considering your program is the only Krawall ripper I've ever heard of, you'd be doing a great service to musicians everywhere.

**Comment by MCJack123** [comment]
MIDI/SF2 and tracked module formats, like XM and S3M that Unkrawerter outputs, are quite different formats, and trying to convert between the two can lose a lot of vital information. MIDI is based off the idea of one instrument per channel (though it can technically change the instrument in the middle), while tracked formats use many instruments on a few channels. MIDI also relies on timed events to activate music, while trackers use a more spreadsheet-like approach, with distinct rows and columns, as well as separated patterns. Trackers have sets of effects that can be applied to a channel in real-time, but MIDI uses more of an open-ended approach, allowing plugins and extensions to send signals instead of specific effects on the audio.

I tried putting together a program to convert .krb bank files into SF2, but quickly found out that it lacks a lot of necessary features. I then tried to use DLS, which sort of works, but isn't super great. [Here's the code for that if you're interested.](https://gist.github.com/MCJack123/bf562f738e7913312f883f6dc9a20008) There are very few programs that can actually tell me what's in the file, and only OpenMPT (which would probably be the one program you're trying NOT to use) would accept it, but only after manually patching the file for some reason. The biggest problems I'm seeing are 1) instrument envelopes are *really* confusing (it uses some sort of source/destination thing, and transforms, and some scale???) and may not even map to how XM does envelopes, and 2) the programs I've found that can convert XM to MIDI lose a *lot* of information. OpenMPT's MIDI export pretty much strips everything except the note events and their volumes and requires manual instrument mapping, and TiMidity++ handles all of the effects/volume based on the instruments for you, but it completely screws up the instrument IDs, making using any sort of normal soundfont file unfeasible.

A middle ground may be to make an SFZ file, which is just a text file that points to the WAV files that Unkrawerter can already spit out for you. OpenMPT has the ability to export these directly from the editor - just open the Instruments tab, click the arrow next to the save (floppy disk) icon, and hit Save All. Then select the folder to save in, select "SFZ Instruments with WAV (*.sfz)" as the file type, and hit Save. That'll rip out all of the instruments from the module into SFZ files with proper envelopes and other settings. I'm not sure what programs can accept this, but it might be useful - I've seen it referenced in a couple of things like MIDI synthesizer programs.

(MuseScore can accept SFZ libraries if you're using that. You can also use [Polyphone](https://www.polyphone-soundfonts.com/forum/support-bug-reports/255-convert-sfz-sf2-via-command-line) to convert SFZ to SF2, but note that this will likely lose some information as I was talking about before.)

Otherwise, I recommend that you stick with the original tracker format that Unkrawerter spits out. It'll be much less painful to deal with than trying to mangle together MIDI/SF2 or DLS. OpenMPT is a great editor, too, and once you get the hang of composing in a tracker it's pretty straightforward to make music in it.
